sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nctri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nctri/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-321898334435"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY